# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 

import sys

class Ui_Chatroom(object):
    def setupUi(self, Chatroom):
        Chatroom.setObjectName("Chatroom")
        Chatroom.resize(908, 473)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Chatroom)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton_2 = QtWidgets.QPushButton(Chatroom)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setText("Disconnect")
        self.pushButton_2.clicked.connect(self.disconnect)

        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.pushButton = QtWidgets.QPushButton(Chatroom)
        self.pushButton.setToolTip("")
        self.pushButton.setToolTipDuration(-1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Send")
        self.pushButton.clicked.connect(self.send)
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)

        self.lineEdit = QtWidgets.QLineEdit(Chatroom)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)

        self.textBrowser = QtWidgets.QTextBrowser(Chatroom)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)


        Chatroom.show()
        QtCore.QMetaObject.connectSlotsByName(Chatroom)

    def disconnect(self):
        print("Disconnected!")
    def send(self):
        print("Message sent!")
        
       

app = QtWidgets.QApplication(sys.argv)
win = QtWidgets.QWidget()

ui = Ui_Chatroom()
ui.setupUi(win)
win.show()
sys.exit(app.exec_())



